import type { FC, SVGProps } from 'react'
import {
  Activity,
  Calendar,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Cloud,
  Download,
  ExternalLink,
  Gauge,
  Heart,
  Home,
  Info,
  LogOut,
  Menu,
  Moon,
  Settings,
  Shield,
  Sparkles,
  Sun,
  Target,
  Trash2,
  TrendingUp,
  User,
  X,
  Zap,
  Bell,
  Search,
  RefreshCw,
} from 'lucide-react'

export type AppIcon = FC<SVGProps<SVGSVGElement>>

export {
  Activity as ActivityIcon,
  Activity as ActiveIcon,
  Bell as BellIcon,
  Calendar as CalendarIcon,
  Check as CheckIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronsUpDown as ChevronDownIcon,
  ChevronsUpDown as ChevronUpIcon,
  Cloud as CloudIcon,
  Download as ExportIcon,
  ExternalLink as ExternalIcon,
  Gauge as GaugeIcon,
  Heart as HeartIcon,
  Home as TodayIcon,
  Home as BodyIcon,
  Info as InfoIcon,
  LogOut as DisconnectIcon,
  Menu as MenuIcon,
  Menu as MinusIcon,
  Menu as PanelLeftIcon,
  Moon as MoonIcon,
  RefreshCw as LoaderIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Shield as ShieldIcon,
  Sparkles as SparkleIcon,
  Sun as SunIcon,
  Target as StepsIcon,
  Target as TargetIcon,
  Trash2 as TrashIcon,
  TrendingUp as TrendIcon,
  User as UserIcon,
  X as CloseIcon,
  Zap as ZapIcon,
  Heart as SleepIcon,
  Activity as DurationIcon,
  Target as DeviceIcon,
  Heart as WaterIcon,
  Activity as CaloriesIcon,
  Activity as NutritionIcon,
  Heart as BreathingIcon,
  Activity as FloorsIcon,
  Gauge as SignalIcon,
  Activity as DistanceIcon,
  Heart as BatteryIcon,
}
